name: CD

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: Release version
        required: false
        default: ''

jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_TOKEN }}
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
      - name: Configure local git
        run: |
          git config user.name "${{ secrets.GIT_USERNAME }}"
          git config user.email "${{ secrets.GIT_USER_EMAIL }}"
      - name: Release new version
        if: ${{ github.event.inputs.release_version == '' }}
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        run: |
          sbt "release cross with-defaults"
      - name: Release the specified version
        if: ${{ github.event.inputs.release_version != '' }}
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        run: |
          sbt "release cross with-defaults release-version ${{ github.event.inputs.release_version }}"
